### ISSUE TITLE
On-demand sync of schemas between GC2 instances

### ISSUE THREAD

**Issue by baffioso** [mapcentia/geocloud2#31]
We have a production and distribution server running GC2 and wold like to be able to replicate schemas from the production to the distribution instance on demand. This feature should only be available for "super users" in GC2. Is it possible to implement in the UI?

**Comment by mapcentia** [comment]
Because the prod server may be behind a firewall we can't use foreign tables in dist server. The prod has to rsync data dumps to dist where they are restored. This can be done by server scripting. These scripts can be run by a Nodejs deamon exposing an rest API for starting scripts. Because a script can run for a long time, its best not to keep the connection but instead use a web socket to push progress info to the browser.
